var annotated_dup =
[
    [ "Debug", "namespace_debug.html", [
      [ "LogEvent", "struct_debug_1_1_log_event.html", "struct_debug_1_1_log_event" ]
    ] ],
    [ "Editor", "namespace_editor.html", [
      [ "AssetBrowser", "class_editor_1_1_asset_browser.html", "class_editor_1_1_asset_browser" ],
      [ "ConsoleLogger", "class_editor_1_1_console_logger.html", "class_editor_1_1_console_logger" ],
      [ "EditorFrame", "class_editor_1_1_editor_frame.html", "class_editor_1_1_editor_frame" ],
      [ "EditorHelper", "class_editor_1_1_editor_helper.html", "class_editor_1_1_editor_helper" ],
      [ "HierarchyPanel", "class_editor_1_1_hierarchy_panel.html", "class_editor_1_1_hierarchy_panel" ],
      [ "Inspector", "class_editor_1_1_inspector.html", "class_editor_1_1_inspector" ],
      [ "MainMenuBar", "class_editor_1_1_main_menu_bar.html", "class_editor_1_1_main_menu_bar" ],
      [ "Viewport", "class_editor_1_1_viewport.html", "class_editor_1_1_viewport" ]
    ] ],
    [ "TakeoffEngine", "namespace_takeoff_engine.html", [
      [ "Camera", "class_takeoff_engine_1_1_camera.html", "class_takeoff_engine_1_1_camera" ],
      [ "Debug", "class_takeoff_engine_1_1_debug.html", "class_takeoff_engine_1_1_debug" ],
      [ "Engine", "class_takeoff_engine_1_1_engine.html", "class_takeoff_engine_1_1_engine" ],
      [ "Entity", "class_takeoff_engine_1_1_entity.html", "class_takeoff_engine_1_1_entity" ],
      [ "GUID", "class_takeoff_engine_1_1_g_u_i_d.html", "class_takeoff_engine_1_1_g_u_i_d" ],
      [ "Hash", "class_takeoff_engine_1_1_hash.html", "class_takeoff_engine_1_1_hash" ],
      [ "IComponent", "class_takeoff_engine_1_1_i_component.html", "class_takeoff_engine_1_1_i_component" ],
      [ "IObject", "class_takeoff_engine_1_1_i_object.html", "class_takeoff_engine_1_1_i_object" ],
      [ "Mat3", "struct_takeoff_engine_1_1_mat3.html", "struct_takeoff_engine_1_1_mat3" ],
      [ "Mat4", "struct_takeoff_engine_1_1_mat4.html", "struct_takeoff_engine_1_1_mat4" ],
      [ "Mathf", "class_takeoff_engine_1_1_mathf.html", "class_takeoff_engine_1_1_mathf" ],
      [ "MonoScriptBase", "class_takeoff_engine_1_1_mono_script_base.html", "class_takeoff_engine_1_1_mono_script_base" ],
      [ "SceneManager", "class_takeoff_engine_1_1_scene_manager.html", "class_takeoff_engine_1_1_scene_manager" ],
      [ "Transform", "class_takeoff_engine_1_1_transform.html", "class_takeoff_engine_1_1_transform" ],
      [ "Vec2", "struct_takeoff_engine_1_1_vec2.html", "struct_takeoff_engine_1_1_vec2" ],
      [ "Vec3", "struct_takeoff_engine_1_1_vec3.html", "struct_takeoff_engine_1_1_vec3" ],
      [ "Vec4", "struct_takeoff_engine_1_1_vec4.html", "struct_takeoff_engine_1_1_vec4" ]
    ] ],
    [ "TE", "namespace_t_e.html", [
      [ "AIManager", "class_t_e_1_1_a_i_manager.html", "class_t_e_1_1_a_i_manager" ],
      [ "AssetsManager", "class_t_e_1_1_assets_manager.html", "class_t_e_1_1_assets_manager" ],
      [ "AStarPather", "class_t_e_1_1_a_star_pather.html", "class_t_e_1_1_a_star_pather" ],
      [ "AudioManager", "class_t_e_1_1_audio_manager.html", "class_t_e_1_1_audio_manager" ],
      [ "AudioSource", "class_t_e_1_1_audio_source.html", "class_t_e_1_1_audio_source" ],
      [ "AudioSystem", "class_t_e_1_1_audio_system.html", "class_t_e_1_1_audio_system" ],
      [ "Blackboard", "class_t_e_1_1_blackboard.html", null ],
      [ "Box", "class_t_e_1_1_box.html", "class_t_e_1_1_box" ],
      [ "BoxCollider", "class_t_e_1_1_box_collider.html", "class_t_e_1_1_box_collider" ],
      [ "BroadPhaseTree", "class_t_e_1_1_broad_phase_tree.html", "class_t_e_1_1_broad_phase_tree" ],
      [ "BVHNode", "class_t_e_1_1_b_v_h_node.html", "class_t_e_1_1_b_v_h_node" ],
      [ "Camera", "class_t_e_1_1_camera.html", "class_t_e_1_1_camera" ],
      [ "Capsule", "class_t_e_1_1_capsule.html", "class_t_e_1_1_capsule" ],
      [ "CapsuleCollider", "class_t_e_1_1_capsule_collider.html", "class_t_e_1_1_capsule_collider" ],
      [ "Collider", "class_t_e_1_1_collider.html", "class_t_e_1_1_collider" ],
      [ "Collision", "class_t_e_1_1_collision.html", "class_t_e_1_1_collision" ],
      [ "CollisionManager", "class_t_e_1_1_collision_manager.html", "class_t_e_1_1_collision_manager" ],
      [ "ComponentRef", "class_t_e_1_1_component_ref.html", "class_t_e_1_1_component_ref" ],
      [ "ComponentRef< Collider >", "class_t_e_1_1_component_ref_3_01_collider_01_4.html", "class_t_e_1_1_component_ref_3_01_collider_01_4" ],
      [ "ComponentRef< IComponent >", "class_t_e_1_1_component_ref_3_01_i_component_01_4.html", "class_t_e_1_1_component_ref_3_01_i_component_01_4" ],
      [ "ComponentRef< MonoScript >", "class_t_e_1_1_component_ref_3_01_mono_script_01_4.html", "class_t_e_1_1_component_ref_3_01_mono_script_01_4" ],
      [ "Contact", "struct_t_e_1_1_contact.html", "struct_t_e_1_1_contact" ],
      [ "ContactListener", "class_t_e_1_1_contact_listener.html", "class_t_e_1_1_contact_listener" ],
      [ "ECSManager", "class_t_e_1_1_e_c_s_manager.html", "class_t_e_1_1_e_c_s_manager" ],
      [ "Engine", "class_t_e_1_1_engine.html", "class_t_e_1_1_engine" ],
      [ "EntityRef", "class_t_e_1_1_entity_ref.html", "class_t_e_1_1_entity_ref" ],
      [ "EXAMPLEMANAGER", "class_t_e_1_1_e_x_a_m_p_l_e_m_a_n_a_g_e_r.html", "class_t_e_1_1_e_x_a_m_p_l_e_m_a_n_a_g_e_r" ],
      [ "Face", "struct_t_e_1_1_face.html", "struct_t_e_1_1_face" ],
      [ "GraphicsManager", "class_t_e_1_1_graphics_manager.html", "class_t_e_1_1_graphics_manager" ],
      [ "GridPos", "struct_t_e_1_1_grid_pos.html", "struct_t_e_1_1_grid_pos" ],
      [ "GUIDCreator", "class_t_e_1_1_g_u_i_d_creator.html", "class_t_e_1_1_g_u_i_d_creator" ],
      [ "HashCreator", "class_t_e_1_1_hash_creator.html", "class_t_e_1_1_hash_creator" ],
      [ "IComponent", "class_t_e_1_1_i_component.html", "class_t_e_1_1_i_component" ],
      [ "IManager", "class_t_e_1_1_i_manager.html", "class_t_e_1_1_i_manager" ],
      [ "InputManager", "class_t_e_1_1_input_manager.html", "class_t_e_1_1_input_manager" ],
      [ "IObject", "class_t_e_1_1_i_object.html", "class_t_e_1_1_i_object" ],
      [ "ISystem", "class_t_e_1_1_i_system.html", "class_t_e_1_1_i_system" ],
      [ "KeysButtons", "struct_t_e_1_1_keys_buttons.html", "struct_t_e_1_1_keys_buttons" ],
      [ "MapLayer", "class_t_e_1_1_map_layer.html", "class_t_e_1_1_map_layer" ],
      [ "Memory", "class_t_e_1_1_memory.html", "class_t_e_1_1_memory" ],
      [ "Mesh", "class_t_e_1_1_mesh.html", "class_t_e_1_1_mesh" ],
      [ "MeshSystem", "class_t_e_1_1_mesh_system.html", "class_t_e_1_1_mesh_system" ],
      [ "MessageBase", "struct_t_e_1_1_message_base.html", null ],
      [ "MonoClassContainer", "class_t_e_1_1_mono_class_container.html", "class_t_e_1_1_mono_class_container" ],
      [ "MonoFieldContainer", "class_t_e_1_1_mono_field_container.html", "class_t_e_1_1_mono_field_container" ],
      [ "MonoMethodContainer", "class_t_e_1_1_mono_method_container.html", "class_t_e_1_1_mono_method_container" ],
      [ "MonoScript", "class_t_e_1_1_mono_script.html", "class_t_e_1_1_mono_script" ],
      [ "MsgReceiver", "struct_t_e_1_1_msg_receiver.html", "struct_t_e_1_1_msg_receiver" ],
      [ "MsgSender", "struct_t_e_1_1_msg_sender.html", "struct_t_e_1_1_msg_sender" ],
      [ "PathRequest", "struct_t_e_1_1_path_request.html", "struct_t_e_1_1_path_request" ],
      [ "PhysicsManager", "class_t_e_1_1_physics_manager.html", "class_t_e_1_1_physics_manager" ],
      [ "RayCastT", "struct_t_e_1_1_ray_cast_t.html", "struct_t_e_1_1_ray_cast_t" ],
      [ "Rigidbody", "class_t_e_1_1_rigidbody.html", "class_t_e_1_1_rigidbody" ],
      [ "Scene", "class_t_e_1_1_scene.html", "class_t_e_1_1_scene" ],
      [ "SceneGraph", "class_t_e_1_1_scene_graph.html", "class_t_e_1_1_scene_graph" ],
      [ "SceneManager", "class_t_e_1_1_scene_manager.html", "class_t_e_1_1_scene_manager" ],
      [ "ScriptLoad", "class_t_e_1_1_script_load.html", "class_t_e_1_1_script_load" ],
      [ "ScriptManager", "class_t_e_1_1_script_manager.html", "class_t_e_1_1_script_manager" ],
      [ "ScriptUpdate", "class_t_e_1_1_script_update.html", "class_t_e_1_1_script_update" ],
      [ "Serializer", "class_t_e_1_1_serializer.html", "class_t_e_1_1_serializer" ],
      [ "Sphere", "class_t_e_1_1_sphere.html", "class_t_e_1_1_sphere" ],
      [ "SphereCollider", "class_t_e_1_1_sphere_collider.html", "class_t_e_1_1_sphere_collider" ],
      [ "Terrain", "class_t_e_1_1_terrain.html", "class_t_e_1_1_terrain" ],
      [ "Texture", "class_t_e_1_1_texture.html", "class_t_e_1_1_texture" ],
      [ "Transform", "class_t_e_1_1_transform.html", "class_t_e_1_1_transform" ],
      [ "Vertex", "struct_t_e_1_1_vertex.html", "struct_t_e_1_1_vertex" ],
      [ "VulkanManager", "class_t_e_1_1_vulkan_manager.html", "class_t_e_1_1_vulkan_manager" ],
      [ "WindowManager", "class_t_e_1_1_window_manager.html", "class_t_e_1_1_window_manager" ],
      [ "WinManagerSettings", "class_t_e_1_1_win_manager_settings.html", "class_t_e_1_1_win_manager_settings" ]
    ] ],
    [ "TRACK", "namespace_t_r_a_c_k.html", [
      [ "Profiler", "class_t_r_a_c_k_1_1_profiler.html", "class_t_r_a_c_k_1_1_profiler" ]
    ] ],
    [ "YAML", "namespace_y_a_m_l.html", [
      [ "convert< glm::ivec2 >", "struct_y_a_m_l_1_1convert_3_01glm_1_1ivec2_01_4.html", "struct_y_a_m_l_1_1convert_3_01glm_1_1ivec2_01_4" ],
      [ "convert< glm::vec2 >", "struct_y_a_m_l_1_1convert_3_01glm_1_1vec2_01_4.html", "struct_y_a_m_l_1_1convert_3_01glm_1_1vec2_01_4" ],
      [ "convert< glm::vec3 >", "struct_y_a_m_l_1_1convert_3_01glm_1_1vec3_01_4.html", "struct_y_a_m_l_1_1convert_3_01glm_1_1vec3_01_4" ],
      [ "convert< glm::vec4 >", "struct_y_a_m_l_1_1convert_3_01glm_1_1vec4_01_4.html", "struct_y_a_m_l_1_1convert_3_01glm_1_1vec4_01_4" ]
    ] ]
];