var annotated_dup =
[
    [ "Debug", null, [
      [ "LogEvent", "struct_debug_1_1_log_event.html", null ]
    ] ],
    [ "Editor", null, [
      [ "AssetBrowser", "class_editor_1_1_asset_browser.html", "class_editor_1_1_asset_browser" ],
      [ "ConsoleLogger", "class_editor_1_1_console_logger.html", "class_editor_1_1_console_logger" ],
      [ "EditorFrame", "class_editor_1_1_editor_frame.html", "class_editor_1_1_editor_frame" ],
      [ "EditorHelper", "class_editor_1_1_editor_helper.html", null ],
      [ "HierarchyPanel", "class_editor_1_1_hierarchy_panel.html", "class_editor_1_1_hierarchy_panel" ],
      [ "ImGui_ImplVulkan_Data", "struct_editor_1_1_im_gui___impl_vulkan___data.html", null ],
      [ "ImGui_ImplVulkan_ViewportData", "struct_editor_1_1_im_gui___impl_vulkan___viewport_data.html", null ],
      [ "ImGui_ImplVulkanH_FrameRenderBuffers", "struct_editor_1_1_im_gui___impl_vulkan_h___frame_render_buffers.html", null ],
      [ "ImGui_ImplVulkanH_WindowRenderBuffers", "struct_editor_1_1_im_gui___impl_vulkan_h___window_render_buffers.html", null ],
      [ "Inspector", "class_editor_1_1_inspector.html", "class_editor_1_1_inspector" ],
      [ "MainMenuBar", "class_editor_1_1_main_menu_bar.html", "class_editor_1_1_main_menu_bar" ],
      [ "Viewport", "class_editor_1_1_viewport.html", "class_editor_1_1_viewport" ]
    ] ],
    [ "TakeoffEngine", "namespace_takeoff_engine.html", [
      [ "AudioSource", "class_takeoff_engine_1_1_audio_source.html", null ],
      [ "BoxCollider", "class_takeoff_engine_1_1_box_collider.html", null ],
      [ "Camera", "class_takeoff_engine_1_1_camera.html", null ],
      [ "CylinderCollider", "class_takeoff_engine_1_1_cylinder_collider.html", null ],
      [ "Entity", "class_takeoff_engine_1_1_entity.html", "class_takeoff_engine_1_1_entity" ],
      [ "IComponent", "class_takeoff_engine_1_1_i_component.html", "class_takeoff_engine_1_1_i_component" ],
      [ "IObject", "class_takeoff_engine_1_1_i_object.html", null ],
      [ "IVec2", "struct_takeoff_engine_1_1_i_vec2.html", null ],
      [ "IVec3", "struct_takeoff_engine_1_1_i_vec3.html", "struct_takeoff_engine_1_1_i_vec3" ],
      [ "Mat3", "struct_takeoff_engine_1_1_mat3.html", null ],
      [ "Mat4", "struct_takeoff_engine_1_1_mat4.html", null ],
      [ "Mesh", "class_takeoff_engine_1_1_mesh.html", null ],
      [ "MonoScriptBase", "class_takeoff_engine_1_1_mono_script_base.html", "class_takeoff_engine_1_1_mono_script_base" ],
      [ "Rigidbody", "class_takeoff_engine_1_1_rigidbody.html", null ],
      [ "SceneManager", "class_takeoff_engine_1_1_scene_manager.html", null ],
      [ "SphereCollider", "class_takeoff_engine_1_1_sphere_collider.html", null ],
      [ "Transform", "class_takeoff_engine_1_1_transform.html", null ],
      [ "Vec2", "struct_takeoff_engine_1_1_vec2.html", "struct_takeoff_engine_1_1_vec2" ],
      [ "Vec3", "struct_takeoff_engine_1_1_vec3.html", "struct_takeoff_engine_1_1_vec3" ],
      [ "Vec4", "struct_takeoff_engine_1_1_vec4.html", "struct_takeoff_engine_1_1_vec4" ]
    ] ],
    [ "TE", "namespace_t_e.html", [
      [ "AIManager", "class_t_e_1_1_a_i_manager.html", null ],
      [ "Animation", "class_t_e_1_1_animation.html", "class_t_e_1_1_animation" ],
      [ "AnimationSystem", "class_t_e_1_1_animation_system.html", null ],
      [ "AssetsManager", "class_t_e_1_1_assets_manager.html", "class_t_e_1_1_assets_manager" ],
      [ "AStarPather", "class_t_e_1_1_a_star_pather.html", "class_t_e_1_1_a_star_pather" ],
      [ "AudioListener", "class_t_e_1_1_audio_listener.html", "class_t_e_1_1_audio_listener" ],
      [ "AudioManager", "class_t_e_1_1_audio_manager.html", "class_t_e_1_1_audio_manager" ],
      [ "AudioSource", "class_t_e_1_1_audio_source.html", "class_t_e_1_1_audio_source" ],
      [ "AudioSystem", "class_t_e_1_1_audio_system.html", "class_t_e_1_1_audio_system" ],
      [ "Blackboard", "class_t_e_1_1_blackboard.html", null ],
      [ "Bone", "struct_t_e_1_1_bone.html", null ],
      [ "Box", "class_t_e_1_1_box.html", "class_t_e_1_1_box" ],
      [ "BoxCollider", "class_t_e_1_1_box_collider.html", "class_t_e_1_1_box_collider" ],
      [ "BPLayerInterfaceImpl", "class_t_e_1_1_b_p_layer_interface_impl.html", null ],
      [ "BroadPhaseTree", "class_t_e_1_1_broad_phase_tree.html", "class_t_e_1_1_broad_phase_tree" ],
      [ "Button", "class_t_e_1_1_button.html", "class_t_e_1_1_button" ],
      [ "BVHNode", "class_t_e_1_1_b_v_h_node.html", "class_t_e_1_1_b_v_h_node" ],
      [ "Camera", "class_t_e_1_1_camera.html", "class_t_e_1_1_camera" ],
      [ "Canvas", "class_t_e_1_1_canvas.html", "class_t_e_1_1_canvas" ],
      [ "Capsule", "class_t_e_1_1_capsule.html", "class_t_e_1_1_capsule" ],
      [ "CapsuleCollider", "class_t_e_1_1_capsule_collider.html", "class_t_e_1_1_capsule_collider" ],
      [ "Collider", "class_t_e_1_1_collider.html", "class_t_e_1_1_collider" ],
      [ "Collision", "class_t_e_1_1_collision.html", null ],
      [ "CollisionManager", "class_t_e_1_1_collision_manager.html", "class_t_e_1_1_collision_manager" ],
      [ "ComponentRef", "class_t_e_1_1_component_ref.html", "class_t_e_1_1_component_ref" ],
      [ "ComponentRef< Collider >", "class_t_e_1_1_component_ref_3_01_collider_01_4.html", "class_t_e_1_1_component_ref_3_01_collider_01_4" ],
      [ "ComponentRef< IComponent >", "class_t_e_1_1_component_ref_3_01_i_component_01_4.html", "class_t_e_1_1_component_ref_3_01_i_component_01_4" ],
      [ "ComponentRef< MonoScript >", "class_t_e_1_1_component_ref_3_01_mono_script_01_4.html", "class_t_e_1_1_component_ref_3_01_mono_script_01_4" ],
      [ "Contact", "struct_t_e_1_1_contact.html", null ],
      [ "CylinderCollider", "class_t_e_1_1_cylinder_collider.html", "class_t_e_1_1_cylinder_collider" ],
      [ "DDSHeader", "struct_t_e_1_1_d_d_s_header.html", null ],
      [ "ECSManager", "class_t_e_1_1_e_c_s_manager.html", "class_t_e_1_1_e_c_s_manager" ],
      [ "Engine", "class_t_e_1_1_engine.html", "class_t_e_1_1_engine" ],
      [ "EntityRef", "class_t_e_1_1_entity_ref.html", "class_t_e_1_1_entity_ref" ],
      [ "EXAMPLEMANAGER", "class_t_e_1_1_e_x_a_m_p_l_e_m_a_n_a_g_e_r.html", null ],
      [ "Face", "struct_t_e_1_1_face.html", null ],
      [ "Font", "struct_t_e_1_1_font.html", null ],
      [ "GraphicsManager", "class_t_e_1_1_graphics_manager.html", "class_t_e_1_1_graphics_manager" ],
      [ "GraphicsObjectResource", "class_t_e_1_1_graphics_object_resource.html", null ],
      [ "GridPos", "struct_t_e_1_1_grid_pos.html", null ],
      [ "GUIDCreator", "class_t_e_1_1_g_u_i_d_creator.html", null ],
      [ "HashCreator", "class_t_e_1_1_hash_creator.html", null ],
      [ "HierarchyNode", "struct_t_e_1_1_hierarchy_node.html", null ],
      [ "IComponent", "class_t_e_1_1_i_component.html", "class_t_e_1_1_i_component" ],
      [ "Image", "class_t_e_1_1_image.html", "class_t_e_1_1_image" ],
      [ "IManager", "class_t_e_1_1_i_manager.html", null ],
      [ "InputManager", "class_t_e_1_1_input_manager.html", "class_t_e_1_1_input_manager" ],
      [ "IObject", "class_t_e_1_1_i_object.html", null ],
      [ "ISystem", "class_t_e_1_1_i_system.html", null ],
      [ "KeysButtons", "struct_t_e_1_1_keys_buttons.html", null ],
      [ "Light", "class_t_e_1_1_light.html", "class_t_e_1_1_light" ],
      [ "Line", "class_t_e_1_1_line.html", null ],
      [ "MapLayer", "class_t_e_1_1_map_layer.html", null ],
      [ "Material", "class_t_e_1_1_material.html", null ],
      [ "MaterialInstance", "class_t_e_1_1_material_instance.html", null ],
      [ "MaterialResource", "class_t_e_1_1_material_resource.html", null ],
      [ "Memory", "class_t_e_1_1_memory.html", null ],
      [ "Mesh", "class_t_e_1_1_mesh.html", "class_t_e_1_1_mesh" ],
      [ "MeshCollider", "class_t_e_1_1_mesh_collider.html", null ],
      [ "MeshResource", "class_t_e_1_1_mesh_resource.html", null ],
      [ "MeshSystem", "class_t_e_1_1_mesh_system.html", null ],
      [ "MessageBase", "struct_t_e_1_1_message_base.html", null ],
      [ "MonoClassContainer", "class_t_e_1_1_mono_class_container.html", "class_t_e_1_1_mono_class_container" ],
      [ "MonoFieldContainer", "class_t_e_1_1_mono_field_container.html", "class_t_e_1_1_mono_field_container" ],
      [ "MonoMethodContainer", "class_t_e_1_1_mono_method_container.html", null ],
      [ "MonoScript", "class_t_e_1_1_mono_script.html", "class_t_e_1_1_mono_script" ],
      [ "MsgReceiver", "struct_t_e_1_1_msg_receiver.html", "struct_t_e_1_1_msg_receiver" ],
      [ "MsgSender", "struct_t_e_1_1_msg_sender.html", "struct_t_e_1_1_msg_sender" ],
      [ "OBB", "class_t_e_1_1_o_b_b.html", "class_t_e_1_1_o_b_b" ],
      [ "ObjectLayerPairFilterImpl", "class_t_e_1_1_object_layer_pair_filter_impl.html", null ],
      [ "ObjectPicker", "class_t_e_1_1_object_picker.html", null ],
      [ "ObjectVsBroadPhaseLayerFilterImpl", "class_t_e_1_1_object_vs_broad_phase_layer_filter_impl.html", null ],
      [ "PathRequest", "struct_t_e_1_1_path_request.html", "struct_t_e_1_1_path_request" ],
      [ "PhysicsManager", "class_t_e_1_1_physics_manager.html", "class_t_e_1_1_physics_manager" ],
      [ "Plane", "class_t_e_1_1_plane.html", null ],
      [ "PrefabComponentContainer", "class_t_e_1_1_prefab_component_container.html", "class_t_e_1_1_prefab_component_container" ],
      [ "PrefabManager", "class_t_e_1_1_prefab_manager.html", "class_t_e_1_1_prefab_manager" ],
      [ "PrefabScriptContainer", "class_t_e_1_1_prefab_script_container.html", null ],
      [ "PrefabSource", "class_t_e_1_1_prefab_source.html", null ],
      [ "RayCast", "struct_t_e_1_1_ray_cast.html", null ],
      [ "RayCastT", "struct_t_e_1_1_ray_cast_t.html", "struct_t_e_1_1_ray_cast_t" ],
      [ "RectTransform", "class_t_e_1_1_rect_transform.html", "class_t_e_1_1_rect_transform" ],
      [ "ResourceGuid", "union_t_e_1_1_resource_guid.html", null ],
      [ "ResourceManager", "class_t_e_1_1_resource_manager.html", null ],
      [ "Resources", "class_t_e_1_1_resources.html", null ],
      [ "Rigidbody", "class_t_e_1_1_rigidbody.html", "class_t_e_1_1_rigidbody" ],
      [ "SafeQueue", "class_t_e_1_1_safe_queue.html", null ],
      [ "Scene", "class_t_e_1_1_scene.html", "class_t_e_1_1_scene" ],
      [ "SceneGraph", "class_t_e_1_1_scene_graph.html", null ],
      [ "SceneManager", "class_t_e_1_1_scene_manager.html", "class_t_e_1_1_scene_manager" ],
      [ "ScriptLoad", "class_t_e_1_1_script_load.html", null ],
      [ "ScriptManager", "class_t_e_1_1_script_manager.html", "class_t_e_1_1_script_manager" ],
      [ "ScriptUpdate", "class_t_e_1_1_script_update.html", null ],
      [ "Segment", "class_t_e_1_1_segment.html", null ],
      [ "Serializer", "class_t_e_1_1_serializer.html", "class_t_e_1_1_serializer" ],
      [ "SkinMesh", "class_t_e_1_1_skin_mesh.html", null ],
      [ "Sphere", "class_t_e_1_1_sphere.html", "class_t_e_1_1_sphere" ],
      [ "SphereCollider", "class_t_e_1_1_sphere_collider.html", "class_t_e_1_1_sphere_collider" ],
      [ "SubMesh", "struct_t_e_1_1_sub_mesh.html", null ],
      [ "TEContactListener", "class_t_e_1_1_t_e_contact_listener.html", null ],
      [ "Terrain", "class_t_e_1_1_terrain.html", "class_t_e_1_1_terrain" ],
      [ "Text", "class_t_e_1_1_text.html", "class_t_e_1_1_text" ],
      [ "Texture", "class_t_e_1_1_texture.html", null ],
      [ "TextureResource", "class_t_e_1_1_texture_resource.html", null ],
      [ "Transform", "class_t_e_1_1_transform.html", "class_t_e_1_1_transform" ],
      [ "Triangle", "class_t_e_1_1_triangle.html", "class_t_e_1_1_triangle" ],
      [ "Vertex", "struct_t_e_1_1_vertex.html", null ],
      [ "VulkanManager", "class_t_e_1_1_vulkan_manager.html", "class_t_e_1_1_vulkan_manager" ],
      [ "WayPoint", "class_t_e_1_1_way_point.html", null ],
      [ "WindowManager", "class_t_e_1_1_window_manager.html", "class_t_e_1_1_window_manager" ],
      [ "WinManagerSettings", "class_t_e_1_1_win_manager_settings.html", null ]
    ] ],
    [ "TRACK", null, [
      [ "Profiler", "class_t_r_a_c_k_1_1_profiler.html", "class_t_r_a_c_k_1_1_profiler" ]
    ] ],
    [ "YAML", null, [
      [ "convert< glm::ivec2 >", "struct_y_a_m_l_1_1convert_3_01glm_1_1ivec2_01_4.html", null ],
      [ "convert< glm::vec2 >", "struct_y_a_m_l_1_1convert_3_01glm_1_1vec2_01_4.html", null ],
      [ "convert< glm::vec3 >", "struct_y_a_m_l_1_1convert_3_01glm_1_1vec3_01_4.html", null ],
      [ "convert< glm::vec4 >", "struct_y_a_m_l_1_1convert_3_01glm_1_1vec4_01_4.html", null ]
    ] ]
];